### ISSUE TITLE
An small error in ReadMe.md?

### ISSUE THREAD

**Issue by hhy150** [allenai/papermage#57]
When I run setup and follow the readme.md,  **pip install -e '.[dev,predictors,visualizers]'**  ,an error occurs:

ERROR: '.[dev,predictors,visualizers]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

After changing to **python install -e .[dev,predictors,visualizers]**, no errors will be reported. I'm not sure if this is a error in ReadMe.md .

**Comment by kyleclo** [comment]
hi @hhy150 ! the quotes seem like needed for install with zsh, not for bash. i can clarify. 

when you say `python install`, do you mean `pip install`?

**Comment by hhy150** [comment]
Yes, I mean `pip install`. Sorry, this is a stupid question. Thank you for your reply.

**Comment by kyleclo** [comment]
no worries; thx for the issue!
