### ISSUE TITLE
Examples mentioned in Papermage paper don't work

### ISSUE THREAD

**Issue by uneetkumarsingh** [allenai/papermage#66]
I was reading through the paper: "PaperMage: A Unified Toolkit for Processing, Representing, and Manipulating Visually-Rich Scientific Documents" and wanted to try the examples in the paper. Below one is not working 
![image](https://github.com/allenai/papermage/assets/79808433/92de7b15-92b0-4047-a0c5-358c93769a1a)

It seems there is no Parser:

Code I am running:

```
import papermage as pm
parser = pm.PDF2TextParser()
```

Error I am getting: 
`AttributeError: module 'papermage' has no attribute 'PDF2TextParser'`

**Comment by kyleclo** [comment]
Hi @uneetkumarsingh. Sorry bout the confusion. The syntax in the paper will not be the exact syntax you need; we have a footnote explaining why this was necessary for the paper:
<img width="391" alt="image" src="https://github.com/allenai/papermage/assets/13603748/f5f67009-46d4-46d1-9888-d63ff826897a">

Instead, we recommend referring more to the GitHub repo's for the latest syntax, especially as code syntax will drift further from the paper over time. This is the snippet you should try instead:

<img width="667" alt="image" src="https://github.com/allenai/papermage/assets/13603748/bc3bcc02-1c07-435c-bd10-1268d256a622">

**Comment by kyleclo** [comment]
Closing now but please re-open if not addressed :)
