### ISSUE TITLE
`ModuleNotFoundError: No module named 'decontext'` trying to import `CoreRecipe`

### ISSUE THREAD

**Issue by eugene-graft** [allenai/papermage#67]
Hi! First of all, thank you for the white paper and the library. The concept of layers is interesting. It's a smart way to represent a document for different purposes.

Unfortunately, I face an issue trying to follow the steps from the README.
Steps to reproduce:

1. `pip install -U papermage`
2. `ipython`
3. `from papermage.recipes import CoreRecipe` => `ModuleNotFoundError: No module named 'decontext'`

Installing the latest version from the source code fixes the issue.

**Comment by kyleclo** [comment]
Thanks for catching @eugene-graft! Some issues with pushing latest version to PyPi. Should be fixed now.  Can you please test:
```
# your fresh environment
pip install 'papermage[dev,predictors,visualizers]'
ipython
from papermage.recipes import CoreRecipe
```

and checking `pip list` should show `papermage == 0.15.0`

**Comment by eugene-graft** [comment]
Works now! Thanks
