### ISSUE TITLE
how to extract figures from the pdf?

### ISSUE THREAD

**Issue by PeterGriffinJin** [allenai/papermage#70]
Hi there,

Thank you so much for the nice package!

Can I ask how to extract the figures from the pdf? I have tried:

recipe = CoreRecipe()
doc = recipe.run("papermage/tests/fixtures/2020.acl-main.447.pdf")
doc.figures

But it seems that this is not returning the figure data. Is the figure extraction achievable with your package?

Best,
Bowen

**Comment by kyleclo** [comment]
Hey @PeterGriffinJin Sorry looks like a bug; once this merges, should fix it thanks!
https://github.com/allenai/papermage/pull/73

**Comment by kyleclo** [comment]
Just merged https://github.com/allenai/papermage/pull/73.  Here's me testing out the recipe locally on that PDF to get Figures:
```
import json
import os
import pathlib

from papermage.magelib import Document
from papermage.recipes import CoreRecipe
from papermage.visualizers.visualizer import plot_entities_on_page

# load doc
recipe = CoreRecipe()
pdfpath = pathlib.Path(__file__).parent.parent / "tests/fixtures/2020.acl-main.447.pdf"
doc = recipe.from_pdf(pdf=pdfpath)
page_id = 0
figures = doc.pages[page_id].intersect_by_box("figures")
plot_entities_on_page(page_image=doc.images[page_id], entities=figures)
```

![image](https://github.com/allenai/papermage/assets/13603748/856eb97c-36f8-4cfd-887b-80a5c3ef6e56)

<img width="652" alt="image" src="https://github.com/allenai/papermage/assets/13603748/7ffbc3ab-8e17-4e04-a383-26c5d1fb2685">

**Comment by kyleclo** [comment]
I'm gonna close this for now, please re-open if it's not resolved, thankss!
